USE PAPER_TRAIL_RECORD_DATA_LOCAL;

SELECT * FROM USER;

SELECT * FROM USER_ACCESS_TOKEN;

-- DELETE FROM RAW_ADDED_ACCOUNT_TRANSACTION;

SELECT * FROM RAW_ADDED_ACCOUNT_TRANSACTION;

SELECT * FROM RAW_MODIFIED_ACCOUNT_TRANSACTION;


-- UPDATE USER_ACCESS_TOKEN set last_cursor = null; 