enum DATABASE_TABLE {
  ACCOUNT_TRANSACTION = "ACCOUNT_TRANSACTION",
  ACCOUNT_TRANSACTION_CATEGORY = "ACCOUNT_TRANSACTION_CATEGORY",
  STG_ADDED_ACCOUNT_TRANSACTION = "STG_ADDED_ACCOUNT_TRANSACTION",
  STG_MODIFIED_ACCOUNT_TRANSACTION = "STG_MODIFIED_ACCOUNT_TRANSACTION",
  STG_REMOVED_ACCOUNT_TRANSACTION = "STG_REMOVED_ACCOUNT_TRANSACTION",
  STG_ACCOUNT_TRANSACTION_CATEGORY = "STG_ACCOUNT_TRANSACTION_CATEGORY",
  USER = "USER",
  USER_ACCESS_TOKEN = "USER_ACCESS_TOKEN",
}

export { DATABASE_TABLE };
