enum DATABASE_TABLE {
  ACCOUNT_TRANSACTION = "ACCOUNT_TRANSACTION",
  ACCOUNT_TRANSACTION_CATEGORY = "ACCOUNT_TRANSACTION_CATEGORY",
  RAW_ADDED_ACCOUNT_TRANSACTION = "RAW_ADDED_ACCOUNT_TRANSACTION",
  RAW_MODIFIED_ACCOUNT_TRANSACTION = "RAW_MODIFIED_ACCOUNT_TRANSACTION",
  RAW_REMOVED_ACCOUNT_TRANSACTION = "RAW_REMOVED_ACCOUNT_TRANSACTION",
  RAW_ACCOUNT_TRANSACTION_CATEGORY = "RAW_ACCOUNT_TRANSACTION_CATEGORY",
  USER = "USER",
  USER_ACCESS_TOKEN = "USER_ACCESS_TOKEN",
}

export { DATABASE_TABLE };
